console.log("giorgi")
console.log("nika")
console.log("luka")
console.log("saba")
console.log("nino")
console.log("zuka")
console.log("davit")
console.log("demetre")
console.log("uflisa")
console.log("goga")
console.log("demetre")
console.log("niko")
console.log("ani")
console.log("gia")
console.log("maia")
 
