let name = prompt("enter name")
alert("hello" + name)
let saurname = prompt("enter saurname") 
alert("hello" + saurname)
let age = prompth("enter your age")
alert("your age is" + age)
let place = prompth("enter your place")
alert("your place is" + place)
let birthDate = prompth("enter your birth date")
alert("your date is" + date)
let height = prompth("enter your height")
alert("your height is" + height)
let weight = prompth("enter your weight")
alert("your weight is " + weight)
 